export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_PENDING = 'GET_PENDING';
export const REMOVE_MESSAGES = 'REMOVE_MESSAGES';
